on: [push]
name: ARM_testing
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.armsecret }}

    - name: ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: e3b99daf-a8ca-4cfd-b706-3eecdcb8a894
        resourceGroupName: testARM
        template: ./storage_account/storageaccount_parameterized.json
        parameters: ./storage_account/parameters.json
